[package]
name = "rust_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0"
rand = "0.8"
rust_ecs_derive = { path = "./rust_ecs_derive" }
chrono = { version = "0.4", features = ["serde"] }
