//! Replay functionality for debugging and analysis
//!
//! This module provides the replay logging and playback capabilities
//! that are core to the ECS framework's debugging features.

use std::fs::{File, OpenOptions};
use std::io::{Write, BufWriter};
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::ecs::system::{WorldUpdateHistory, WorldUpdateDiff};

/// Configuration for automatic replay logging
#[derive(Debug, Clone)]
pub struct ReplayLogConfig {
    /// Whether logging is enabled
    pub enabled: bool,
    /// Directory to save replay files
    pub log_directory: String,
    /// Base name for log files (timestamp will be appended)
    pub file_prefix: String,
    /// Maximum number of updates to keep in memory before flushing to disk
    pub flush_interval: usize,
    /// Whether to include detailed component changes in logs
    pub include_component_details: bool,
}

impl Default for ReplayLogConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            log_directory: "replay_logs".to_string(),
            file_prefix: "game_replay".to_string(),
            flush_interval: 100,
            include_component_details: true,
        }
    }
}

/// Automatic replay logger that saves game history to files for analysis
#[derive(Debug)]
pub struct AutoReplayLogger {
    config: ReplayLogConfig,
    log_file: Option<BufWriter<File>>,
    session_id: String,
    update_count: usize,
}

impl AutoReplayLogger {
    /// Create a new auto replay logger with the given configuration
    pub fn new(config: ReplayLogConfig) -> Self {
        let session_id = Self::generate_session_id();
        
        Self {
            config,
            log_file: None,
            session_id,
            update_count: 0,
        }
    }

    /// Initialize the logger by creating the log file
    pub fn initialize(&mut self) -> Result<(), std::io::Error> {
        if !self.config.enabled {
            return Ok(());
        }

        // Create the log directory if it doesn't exist
        std::fs::create_dir_all(&self.config.log_directory)?;

        // Create the log file path
        let log_file_path = format!(
            "{}/{}_{}.log",
            self.config.log_directory,
            self.config.file_prefix,
            self.session_id
        );

        // Create or truncate the log file
        let log_file = OpenOptions::new()
            .create(true)
            .write(true)
            .truncate(true)
            .open(&log_file_path)?;

        let mut writer = BufWriter::new(log_file);

        // Write initial headers
        writeln!(writer, "# Replay Log Generated by Rust ECS Framework")?;
        writeln!(writer, "# Session ID: {}", self.session_id)?;
        writeln!(writer, "# Generated: {}", Self::current_timestamp())?;
        writeln!(writer, "# Format: Component changes and world operations per update")?;
        writeln!(writer)?;

        self.log_file = Some(writer);

        println!("Replay logging initialized");
        println!("Session ID: {}", self.session_id);
        println!("Log file: {}", log_file_path);

        Ok(())
    }

    /// Log a world update to the replay file
    pub fn log_update(&mut self, update_diff: &WorldUpdateDiff) -> Result<(), std::io::Error> {
        if !self.config.enabled || self.log_file.is_none() {
            return Ok(());
        }

        self.update_count += 1;

        if let Some(ref mut file) = self.log_file {
            writeln!(file, "UPDATE {}", self.update_count)?;
            writeln!(file, "SYSTEMS: {}", update_diff.system_diffs().len())?;

            for (system_index, system_diff) in update_diff.system_diffs().iter().enumerate() {
                writeln!(file, "  SYSTEM {}", system_index)?;
                
                if self.config.include_component_details {
                    writeln!(file, "    COMPONENT_CHANGES: {}", system_diff.diff_changes().len())?;
                    for change in system_diff.diff_changes() {
                        writeln!(file, "      {:?}", change)?;
                    }
                    
                    writeln!(file, "    WORLD_OPERATIONS: {}", system_diff.world_operations().len())?;
                    for operation in system_diff.world_operations() {
                        writeln!(file, "      {:?}", operation)?;
                    }
                } else {
                    writeln!(file, "    COMPONENT_CHANGES: {}", system_diff.component_changes().len())?;
                    writeln!(file, "    WORLD_OPERATIONS: {}", system_diff.world_operations().len())?;
                }
            }
            
            writeln!(file)?; // Empty line for readability

            // Flush periodically or when requested
            if self.update_count % self.config.flush_interval == 0 {
                file.flush()?;
            }
        }

        Ok(())
    }

    /// Finalize the log file and close it
    pub fn finalize(&mut self) -> Result<(), std::io::Error> {
        if let Some(mut file) = self.log_file.take() {
            writeln!(file, "# End of replay log - Total updates: {}", self.update_count)?;
            file.flush()?;
        }
        Ok(())
    }

    /// Get the current session ID
    pub fn session_id(&self) -> &str {
        &self.session_id
    }

    /// Get the current update count
    pub fn update_count(&self) -> usize {
        self.update_count
    }

    /// Generate a unique session ID based on timestamp
    fn generate_session_id() -> String {
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs()
            .to_string()
    }

    /// Get current timestamp as a formatted string
    fn current_timestamp() -> String {
        match SystemTime::now().duration_since(UNIX_EPOCH) {
            Ok(duration) => {
                let secs = duration.as_secs();
                format!("Unix timestamp: {}", secs)
            }
            Err(_) => "Unknown time".to_string(),
        }
    }
}

/// Replay data analysis utilities for developers
pub mod analysis {
    use super::*;
    use crate::ecs::diff::DiffComponentChange;
    use crate::ecs::core::Entity;

    /// Statistics about a replay log
    #[derive(Debug)]
    pub struct ReplayStats {
        pub total_updates: usize,
        pub total_system_executions: usize,
        pub total_component_changes: usize,
        pub total_world_operations: usize,
        pub unique_entities: std::collections::HashSet<Entity>,
    }

    /// Parse a replay log file and return statistics
    pub fn analyze_replay_log(file_path: &str) -> Result<ReplayStats, Box<dyn std::error::Error>> {
        let content = std::fs::read_to_string(file_path)?;
        
        let mut stats = ReplayStats {
            total_updates: 0,
            total_system_executions: 0,
            total_component_changes: 0,
            total_world_operations: 0,
            unique_entities: std::collections::HashSet::new(),
        };

        for line in content.lines() {
            if line.starts_with("UPDATE ") {
                stats.total_updates += 1;
            } else if line.trim().starts_with("SYSTEM ") {
                stats.total_system_executions += 1;
            } else if line.trim().starts_with("COMPONENT_CHANGES: ") {
                if let Some(count_str) = line.split(": ").nth(1) {
                    if let Ok(count) = count_str.parse::<usize>() {
                        stats.total_component_changes += count;
                    }
                }
            } else if line.trim().starts_with("WORLD_OPERATIONS: ") {
                if let Some(count_str) = line.split(": ").nth(1) {
                    if let Ok(count) = count_str.parse::<usize>() {
                        stats.total_world_operations += count;
                    }
                }
            }
            // Parse entity information from component changes
            else if line.trim().starts_with("MOD Entity(") || line.trim().starts_with("ADD Entity(") || line.trim().starts_with("REM Entity(") {
                if let Some(entity) = parse_entity_from_line(line) {
                    stats.unique_entities.insert(entity);
                }
            }
        }

        Ok(stats)
    }

    /// Parse an entity from a replay log line
    fn parse_entity_from_line(line: &str) -> Option<Entity> {
        // Look for pattern like "Entity(0, 123)"
        if let Some(start) = line.find("Entity(") {
            if let Some(end) = line[start..].find(")") {
                let entity_str = &line[start + 7..start + end];
                let parts: Vec<&str> = entity_str.split(", ").collect();
                if parts.len() == 2 {
                    if let (Ok(gen), Ok(id)) = (parts[0].parse::<usize>(), parts[1].parse::<usize>()) {
                        return Some(Entity::new(id, gen));
                    }
                }
            }
        }
        None
    }

    /// Parse a replay log file and return the parsed history
    pub fn parse_replay_log(file_path: &str) -> Result<WorldUpdateHistory, Box<dyn std::error::Error>> {
        let _content = std::fs::read_to_string(file_path)?;
        
        // For now, return an empty history
        // A full implementation would parse the file and reconstruct the history
        let history = WorldUpdateHistory::new();
        
        Ok(history)
    }
}